### ISSUE TITLE
مشکل از استفاده از سورس کد

### ISSUE THREAD

**Issue by shahabsaalami** [persian-calendar/calendar#52]
با سلام 
ممنون از اینکه وقت با ارزشوتن برای توسعه این کتابخانه های اپن سروس سپری کردین.
فقط من مشکلی دارم مستندات خیلی ضعیف هست، برای استفاده یا باید کل پروژه بررسی بشه تا متوجه بشه چطوری استفاده کرد. 
به عنوان مثلا میخواستم از `PersianDate` استفاده کنم و وقتی پارامتر ورودی System.currentTimeMillis() میدادم کرش میکرد. کد بررسی کردم دیدم ونوشته jdn ، ولی متوجه نشدم jdn چی هست.
اگر مستندات وجود داشته باشه خیلی کمک میکنه، اگر کمکی هم از دست من برمیاد حتما خوشحال میشم یک گوشه کار هم من بگیرم.

**Comment by shahabsaalami** [comment]
خطا: 
`java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1
                                                     	at io.github.persiancalendar.calendar.persian.AlgorithmicConverter.daysInPreviousMonths(AlgorithmicConverter.java:70)
                                                     	at io.github.persiancalendar.calendar.persian.AlgorithmicConverter.fromJdn(AlgorithmicConverter.java:65)
                                                     	at io.github.persiancalendar.calendar.PersianDate.fromJdn(PersianDate.java:30)
                                                     	at io.github.persiancalendar.calendar.AbstractDate.<init>(AbstractDate.java:32)
                                                     	at io.github.persiancalendar.calendar.PersianDate.<init>(PersianDate.java:13)`

**Comment by ebraminio** [comment]
سلام گرامی درست می‌فرمایید سعی شده این کتابخانه مستقیم با سیستم ارتباطی نداشته باشه و به خاطر همین ورودی currentTimeMillis نیز ندارد و ورودی آن از تاریخ است، مثلاً در این تست نحوهٔ استفاده از آن قرار دارد https://github.com/persian-calendar/calendar/blob/main/src/test/kotlin/io/github/persiancalendar/calendar/MainTests.kt#L28-L90 البته بگویم یکی از دلایلی که چندان تآکیدی روی مستندات این کتابخانه نکرده‌ام این است که شروع این این کدی از کدی دیگر که با مجوز GPL استفاده منتشر شده بود استفاده کرده (از آن موقع البته خیلی از قسمت‌های کد تغییر کرده ولی با این حال همه این سال‌ها مشارکت‌ها با آن مجوز انجام شده است) و به همین دلیل خود این کد هم دارای مجوز GPL است که در اینجا توضیح بیشتری دربارهٔ آن داده‌ام https://github.com/persian-calendar/persian-calendar?tab=readme-ov-file#مجوز-شرایط-استفاده-از-کد-برنامه یکی از مسائلی که همهٔ آن درگیر آن بوده‌ام تقویم قمری ایران است اگر شخصی الگوریتم پایهٔ محاسبهٔ تقویم قمری ایران که مرکز تقویم دانشگاه تهران از آن هر ساله برای انتشار ماه‌های قمری سال بعد استفاده می‌کند بیابد فوق‌العاده خواهد بود، ممنونم 😊🙏

**Comment by ebraminio** [comment]
https://github.com/persian-calendar/calendar/issues/1#issuecomment-699526493
